insert into public.locations (
  slug,
  name,
  address_line,
  city,
  state,
  postal_code,
  lat,
  lng,
  geocode_status,
  category,
  distribution_day,
  next_distribution_dates,
  distribution_time_text,
  availability_status,
  enrollment_frequency,
  enrollment_time_text,
  additional_languages,
  additional_info,
  zip_codes_served,
  outside_zip_code,
  source_url,
  active
)
values
  (
    'webster-eddy-food-pantry-94115',
    'Webster Eddy Food Pantry',
    '1280 Webster St',
    'San Francisco',
    'CA',
    '94115',
    37.7837,
    -122.4296,
    'success',
    'weekly_groceries',
    'Wednesday',
    array['Wednesday, 5/20', 'Wednesday, 5/27', 'Wednesday, 6/03', 'Wednesday, 6/10'],
    '8:30 am - 9:30 am',
    'Enrollment spaces available',
    'Every distribution',
    '9:15 am',
    '{}'::text[],
    array['Accessible Entrance'],
    array['San Francisco County'],
    true,
    'https://foodlocator.sfmfoodbank.org/en/sf/94108/urgent/calfresh',
    true
  ),
  (
    'city-team-food-pantry-94103',
    'City Team Food Pantry',
    '164 6th St',
    'San Francisco',
    'CA',
    '94103',
    37.7783,
    -122.4085,
    'success',
    'weekly_groceries',
    'Monday',
    array['Monday, 5/18', 'Monday, 6/01', 'Monday, 6/08', 'Monday, 6/15'],
    '10:00 am - 11:00 am',
    'Enrollment spaces available',
    'Every distribution',
    '11:00 am',
    '{}'::text[],
    array[
      'Accessible Entrance',
      'Minimal cooking menu: This pantry has food intended for people with minimal cooking facilities and/or cold storage.'
    ],
    array['San Francisco County'],
    true,
    'https://foodlocator.sfmfoodbank.org/en/sf/94108/urgent/calfresh',
    true
  ),
  (
    'chinatown-ymca-94108',
    'Chinatown YMCA',
    '1 Sabin Pl',
    'San Francisco',
    'CA',
    '94108',
    37.7946,
    -122.4067,
    'success',
    'weekly_groceries',
    'Thursday',
    array['Thursday, 5/21', 'Thursday, 5/28', 'Thursday, 6/04', 'Thursday, 6/11'],
    '2:30 pm - 4:00 pm',
    'Waitlist Only',
    'Every distribution',
    '5:30 pm',
    array['CANTONESE', 'MANDARIN'],
    array['Accessible Entrance'],
    array['94108', '94111', '94133'],
    false,
    'https://foodlocator.sfmfoodbank.org/en/sf/94108/urgent/calfresh',
    true
  )
on conflict (slug) do update
set
  name = excluded.name,
  address_line = excluded.address_line,
  city = excluded.city,
  state = excluded.state,
  postal_code = excluded.postal_code,
  lat = excluded.lat,
  lng = excluded.lng,
  geocode_status = excluded.geocode_status,
  category = excluded.category,
  distribution_day = excluded.distribution_day,
  next_distribution_dates = excluded.next_distribution_dates,
  distribution_time_text = excluded.distribution_time_text,
  availability_status = excluded.availability_status,
  enrollment_frequency = excluded.enrollment_frequency,
  enrollment_time_text = excluded.enrollment_time_text,
  additional_languages = excluded.additional_languages,
  additional_info = excluded.additional_info,
  zip_codes_served = excluded.zip_codes_served,
  outside_zip_code = excluded.outside_zip_code,
  source_url = excluded.source_url,
  active = excluded.active;
