// =============================================================================
// TEMPLATE / MOCK DATA — DELETE THIS FILE when Supabase is connected.
// In app/page.tsx, replace `import { MOCK_LOCATIONS }` with a Supabase fetch.
// =============================================================================

import type { Location } from "./types";

export const MOCK_LOCATIONS: Location[] = [
  {
    id: "mock-1",
    slug: "webster-eddy-food-pantry-94115",
    name: "Webster Eddy Food Pantry",
    addressLine: "1280 Webster St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94115",
    lat: 37.7837,
    lng: -122.4296,
    geocodeStatus: "success",
    category: "weekly_groceries",
    distributionDay: "Wednesday",
    nextDistributionDates: ["Wednesday, 5/20", "Wednesday, 5/27", "Wednesday, 6/03", "Wednesday, 6/10"],
    distributionTimeText: "8:30 am - 9:30 am",
    availabilityStatus: "Enrollment spaces available",
    enrollmentFrequency: "Every distribution",
    enrollmentTimeText: "9:15 am",
    additionalLanguages: [],
    additionalInfo: ["Accessible Entrance"],
    zipCodesServed: ["San Francisco County"],
    outsideZipCode: true,
    sourceUrl: "https://foodlocator.sfmfoodbank.org/en/sf/94108/urgent/calfresh",
    siteUrl: null,
    active: true,
    lastScrapedAt: null,
    lastChangedAt: null,
  },
  {
    id: "mock-2",
    slug: "city-team-food-pantry-94103",
    name: "City Team Food Pantry",
    addressLine: "164 6th St",
    city: "San Francisco",
    state: "CA",
    postalCode: "94103",
    lat: 37.7783,
    lng: -122.4085,
    geocodeStatus: "success",
    category: "weekly_groceries",
    distributionDay: "Monday",
    nextDistributionDates: ["Monday, 5/18", "Monday, 6/01", "Monday, 6/08", "Monday, 6/15"],
    distributionTimeText: "10:00 am - 11:00 am",
    availabilityStatus: "Enrollment spaces available",
    enrollmentFrequency: "Every distribution",
    enrollmentTimeText: "11:00 am",
    additionalLanguages: [],
    additionalInfo: [
      "Accessible Entrance",
      "Minimal cooking menu: This pantry has food intended for people with minimal cooking facilities and/or cold storage.",
    ],
    zipCodesServed: ["San Francisco County"],
    outsideZipCode: true,
    sourceUrl: "https://foodlocator.sfmfoodbank.org/en/sf/94108/urgent/calfresh",
    siteUrl: null,
    active: true,
    lastScrapedAt: null,
    lastChangedAt: null,
  },
  {
    id: "mock-3",
    slug: "chinatown-ymca-94108",
    name: "Chinatown YMCA",
    addressLine: "1 Sabin Pl",
    city: "San Francisco",
    state: "CA",
    postalCode: "94108",
    lat: 37.7946,
    lng: -122.4067,
    geocodeStatus: "success",
    category: "weekly_groceries",
    distributionDay: "Thursday",
    nextDistributionDates: ["Thursday, 5/21", "Thursday, 5/28", "Thursday, 6/04", "Thursday, 6/11"],
    distributionTimeText: "2:30 pm - 4:00 pm",
    availabilityStatus: "Waitlist Only",
    enrollmentFrequency: "Every distribution",
    enrollmentTimeText: "5:30 pm",
    additionalLanguages: ["CANTONESE", "MANDARIN"],
    additionalInfo: ["Accessible Entrance"],
    zipCodesServed: ["94108", "94111", "94133"],
    outsideZipCode: false,
    sourceUrl: "https://foodlocator.sfmfoodbank.org/en/sf/94108/urgent/calfresh",
    siteUrl: null,
    active: true,
    lastScrapedAt: null,
    lastChangedAt: null,
  },
];
